name: Deploy Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 26

      - name: Install Dependencies
        run: npm install --prefix frontend

      - name: Fix permissions for Linux runner
        run: chmod +x frontend/node_modules/.bin/react-scripts || true

      - name: Build Project
        run: npm run build --prefix frontend

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy frontend/build --project-name=desafio-plus --commit-dirty=true
